### ISSUE TITLE
Issue in scorer.py

### ISSUE THREAD

**Issue by jndevanshu** [attapol/conll16st#10]
I am having the following error on running the scorer.py script:

**================================================
Evaluation for all discourse relations
Traceback (most recent call last):
  File "scorer.py", line 264, in <module>
    main()
  File "scorer.py", line 249, in main
    evaluate(gold_list, predicted_list)
  File "scorer.py", line 16, in evaluate
    connective_cm = evaluate_connectives(gold_list, predicted_list)
  File "scorer.py", line 60, in evaluate_connectives
    explicit_gold_list, explicit_predicted_list, connective_head_matching)  
  File "scorer.py", line 200, in compute_binary_eval_metric
    if matching_fn(gold_span, predicted_span) and not matched_predicted[i]:
  File "scorer.py", line 127, in connective_head_matching
    elif not set(predicted_token_list).issubset(set(gold_token_indices)):
TypeError: unhashable type: 'list'**

Please help me regarding the same.

**Comment by attapol** [comment]
Run the validator first. That should help identifying the problem. 
TokenList field must be a list of integers not a list of lists.
