### ISSUE TITLE
Index Error of function 'evaluate_sense' in score.py

### ISSUE THREAD

**Issue by qcl6355** [attapol/conll16st#5]
➜  conll2016 git:(master) ✗ python ~/WorkSpace/conll2016/conll16st/scorer.py ~/corpora/conll16st-en-zh-dev-train/conll16st-en-01-12-16-dev/relations.json report/dev.output.json
# 

Evaluation for all discourse relations
Traceback (most recent call last):
  File "/Users/Sheng/WorkSpace/conll2016/conll16st/scorer.py", line 262, in <module>
    main()
  File "/Users/Sheng/WorkSpace/conll2016/conll16st/scorer.py", line 247, in main
    evaluate(gold_list, predicted_list)
  File "/Users/Sheng/WorkSpace/conll2016/conll16st/scorer.py", line 18, in evaluate
    sense_cm = evaluate_sense(gold_list, predicted_list)
  File "/Users/Sheng/WorkSpace/conll2016/conll16st/scorer.py", line 162, in evaluate_sense
    sense_cm.add(predicted_sense, gold_relation['Sense'][0])
  File "/Users/Sheng/WorkSpace/conll2016/conll16st/confusion_matrix.py", line 48, in add
    self.matrix[prediction_index, true_answer_index] += 1
IndexError: index 15 is out of bounds for axis 1 with size 15

This error was caused by some gold senses are not in valid_senses (see line 145 in score.py). Could we  remove the if expression ?

**Comment by attapol** [comment]
Instead the gold relations that have invalid senses should be ignored. I just made a new commit to fix this.
